version: 2.1
jobs:
  build:
   docker:
      - image: fr3akyphantom/droid-builder:latest
   environment:
      GIT_EMAIL: 'dhruvtadvi777@gmail.com'
      GIT_NAME: 'dhruv'
      VERSION: '3.0.0'
      PBRP_MANIFEST: 'android-10.0'
      VENDOR: 'tecno'
      DEVICE: 'KE6'
   steps:
      - setup_remote_docker:
          version: 19.03.8
      - run:
          name: "PBRP Builder"
          command: |
            sudo apt-get install zstd xz-utils -y
            wget https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.4.0-20201103/MinimalOmniRecovery-twrp-6.0-norepo-20201103.tzst
            tar --zstd -xf MinimalOmniRecovery-twrp-6.0-norepo-20201103.tzst
           
workflows:
  version: 2.1
  remote_builder:
    jobs:
      - build:
          context: org-global
