version: 2.1
jobs:
  build:
   docker:
      - image: ubuntu:18.04
   environment:
      GIT_EMAIL: 'dhruvtadvi777@gmail.com'
      GIT_NAME: 'dhruv'
      VERSION: '3.0.0'
      PBRP_MANIFEST: 'android-10.0'
      VENDOR: 'tecno'
      DEVICE: 'KE6'
   steps:
      - setup_remote_docker:
          version: 19.03.8
      - run:
          name: "PBRP Builder"
          command: |
           echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc bison build-essential curl flex g++-multilib gcc python3 gcc-multilib clang git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev unzip openjdk-8-jdk python ccache libtinfo5 repo libstdc++6 wget libssl-dev rsync
           mkdir -p ~/bin
           curl https://storage.googleapis.com/git-repo-downloads/repo-1 > ~/bin/repo
           chmod a+x ~/bin/repo
           git config --global user.email "${GIT_EMAIL}"
           git config --global user.name "{GIT_NAME}"
           git config --global color.ui false
           python3 ~/bin/repo init --depth=1 -u https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-9.0
           python3 ~/bin/repo sync
           git clone https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} device/${VENDOR}/${DEVICE}
           export ALLOW_MISSING_DEPENDENCIES=true
           export LC_ALL=C
           source build/envsetup.sh
           lunch omni_${DEVICE}-eng
           mka recoveryimage -j4
           curl -F document=@"/out/target/product/tecno/PBRP*.zip" https://api.telegram.org/bot5850627331:AAEUPnaCSRpgPbANNPFmvZeT2POvGE_7eV4/sendDocument?chat_id=6000924101
workflows:
  version: 2.1
  remote_builder:
    jobs:
      - build:
          context: org-global
