version: 2.1
jobs:
  build:
   docker:
      - image: fr3akyphantom/droid-builder:latest
   environment:
      GIT_EMAIL: 'dhruvtadvi777@gmail.com'
      GIT_NAME: 'dhruv'
      VERSION: '3.0.0'
      PBRP_MANIFEST: 'android-10.0'
      VENDOR: 'tecno'
      DEVICE: 'KE6'
   steps:
      - setup_remote_docker:
          version: 19.03.8
      - run:
          name: "PBRP Builder"
          command: |
            sudo apt-get -y update && apt-get -y upgrade && apt-get -y install python3 bc bison build-essential curl flex g++-multilib gcc gcc-multilib clang git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev unzip openjdk-8-jdk python ccache libtinfo5 repo libstdc++6 wget libssl-dev rsync
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            git config --global user.email "${GIT_EMAIL}"
            git config --global user.name "{GIT_NAME}"
            git config --global color.ui false
            python3 ~/bin/repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-9.0
            python3 ~/bin/repo sync
            source build/envsetup.sh
            git clone https://github.com/dhruvtadvi/android_device_tecno_TECNO-KE6 ./device/tecno/KE6
            lunch omni_KE6-userdebug
            make -j$(nproc--all) recoveryimage
            curl -F document=@"/out/target/product/KE6/recovery.img" https://api.telegram.org/bot6191024484:AAHJ844J3C07Ar9lsekpETxsfMsHbKlwBcQ/sendDocument?chat_id=1600658409
workflows:
  version: 2.1
  remote_builder:
    jobs:
      - build:
          context: org-global
