version: 2.1
jobs:
  build:
   docker:
      - image: ubuntu:18.04
   environment:
      GIT_EMAIL: 'dhruvtadvi777@gmail.com'
      GIT_NAME: 'dhruv'
      VERSION: '3.0.0'
      PBRP_MANIFEST: 'android-10.0'
      VENDOR: 'tecno'
      DEVICE: 'KE6'
   steps:
      - setup_remote_docker:
          version: 19.03.8
      - run:
          name: "PBRP Builder"
          command: |
            apt update -y && apt upgrade -y
            apt install wget -y
            wget https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.5.0_9-20210130/MinimalOmniRecovery-twrp-9.0-norepo-20210130.tzst.ab
            tar --use-compress-program=unzstd -xvf MinimalOmniRecovery-twrp-9.0-norepo-20210130.tzst.*
           
workflows:
  version: 2.1
  remote_builder:
    jobs:
      - build:
          context: org-global
